version: '3.1'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: hospitalDB
    ports:
      - 3306:3306

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 5600
      MONGO_INITDB_DATABASE: chat
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  hospital-container:
    restart: always
    image: hospital-manager
    ports:
      - 2797:2797
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql
      - mongo

  angular:
    build:
      context: ./hospitalManageFrontend
      dockerfile: Dockerfile-angular
    ports:
      - 4200:4200
    container_name: angular
    volumes:
      - ./hospitalManageFrontend:/usr/src/app/hospitalManageFrontend
      - /usr/src/app/hospitalManageFrontend/node_modules



