jwt:
  secter: '[a-zA-Z0-9._]@+$Guidelines89797987forAlpabeticalArraNumeralsandOtherSybo$'

server:
  port: 2632
  error:
    path: /error
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospitalDB
    username: root
    password:
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    oauth2:
      client:
        client-id: 3b2ac02f-a5c8-4c74-afea-500b6287c44b_fabf988d-9c47-4d6f-8583-7de576a5a92c
        client-secret: S4X69dzZ9IsBfseUoMy00GqmQj9A3SyvimasYRFY0as=
        introspection-uri: https://icdaccessmanagement.who.int/connect/token
        grand-type: client_credentials
        scope: icdapi_access
