jwt:
  secter: '[a-zA-Z0-9._]@+$Guidelines89797987forAlpabeticalArraNumeralsandOtherSybo$'

server:
  port: 2797
  error:
    path: /error
spring:
  data:
    mongodb:
      uri: mongodb://root:5600@127.0.0.1:27017/chat?authSource=chat&readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false
  datasource:
    url: jdbc:mysql://localhost:3306/hospitalDB
    username: root
    password:
#        uri: mongodb://root:5600@mongo:27017/chat?authSource=chat
#  datasource:
#        url: jdbc:mysql://mysql:3306/hospitalDB
#        username: root
#        password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  jpa:
    show_sql: true
    hibernate:
      jdbc:
        batch_size: 50
        fetch_size: 50
        max_size: 25
        min_size: 5
      dialect: org.hibernate.dialect.MySQL5Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



  security:
    oauth2:
      client:
        client-id: 3b2ac02f-a5c8-4c74-afea-500b6287c44b_fabf988d-9c47-4d6f-8583-7de576a5a92c
        client-secret: S4X69dzZ9IsBfseUoMy00GqmQj9A3SyvimasYRFY0as=
        introspection-uri: https://icdaccessmanagement.who.int/connect/token
        grand-type: client_credentials
        scope: icdapi_access
logging:
  level:
    web:
      socket: trace
