jwt:
  secter: '[a-zA-Z0-9._]@+$Guidelines89797987forAlpabeticalArraNumeralsandOtherSybo$'

server:
  port: 2321
  error:
    path: /error
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospitalDB
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
